spring:
  application:
    name: config-server
  cloud:
      config:
        server:
          git:
            uri:  https://github.com/phantomedc/springcloud-learn/common-config/
        label: master
server:
  port: 8888

