eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
server:
  port: 8888


spring:
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/phantomedc/springcloud-learn/
          searchPaths:  common-config
    label: master